import { OutfitSuggestion } from '@/components/chat/OutfitSuggestionRow'

export const sampleOutfits: OutfitSuggestion[] = [
  {
    id: 'outfit-1',
    title: 'Bright & Minimal',
    number: 1,
    tag: 'Wardrobe',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    total: '$0',
    products: [
      {
        id: 'product-1',
        name: 'Basic Quarter-Zip Sweatshirt',
        price: '$45.99',
        brand: 'Zara',
        image: '/images/onboarding/stack/stack-image-2.png',
        isLiked: false,
        isSaved: false,
      },
      {
        id: 'product-2',
        name: 'Washed Effect Carpenter Jeans',
        price: '$45.99',
        brand: 'Zara',
        image: '/images/onboarding/stack/stack-image-3.png',
        isLiked: false,
        isSaved: false,
      },
      {
        id: 'product-3',
        name: 'Monochrome Chunky Sneakers',
        price: '$45.99',
        brand: 'Zara',
        image: '/images/onboarding/stack/stack-image-4.png',
        isLiked: false,
        isSaved: false,
      },
      {
        id: 'product-4',
        name: 'Squared Sunglasses',
        price: '$45.99',
        brand: 'Zara',
        image: '/images/onboarding/stack/stack-image-5.png',
        isLiked: false,
        isSaved: false,
      },
    ],
  },
  {
    id: 'outfit-2',
    title: 'Bright & Minimal',
    number: 2,
    tag: 'Wardrobe + Shopping',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    total: '$183.96',
    products: [
      {
        id: 'product-5',
        name: 'Basic Quarter-Zip Sweatshirt',
        price: '$45.99',
        brand: 'Zara',
        image: '',
        isLiked: false,
        isSaved: false,
      },
      {
        id: 'product-6',
        name: 'Washed Effect Carpenter Jeans',
        price: '$45.99',
        brand: 'Zara',
        image: '',
        isLiked: false,
        isSaved: false,
      },
      {
        id: 'product-7',
        name: 'Monochrome Chunky Sneakers',
        price: '$45.99',
        brand: 'Zara',
        image: '',
        isLiked: false,
        isSaved: false,
      },
      {
        id: 'product-8',
        name: 'Squared Sunglasses',
        price: '$45.99',
        brand: 'Zara',
        image: '',
        isLiked: false,
        isSaved: false,
      },
    ],
  },
  {
    id: 'outfit-3',
    title: 'Bright & Minimal',
    number: 3,
    tag: 'Shopping',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    total: '$183.96',
    products: [
      {
        id: 'product-9',
        name: 'Basic Quarter-Zip Sweatshirt',
        price: '$45.99',
        brand: 'Zara',
        image: '',
        isLiked: false,
        isSaved: false,
      },
      {
        id: 'product-10',
        name: 'Washed Effect Carpenter Jeans',
        price: '$45.99',
        brand: 'Zara',
        image: '',
        isLiked: false,
        isSaved: false,
      },
      {
        id: 'product-11',
        name: 'Monochrome Chunky Sneakers',
        price: '$45.99',
        brand: 'Zara',
        image: '',
        isLiked: false,
        isSaved: false,
      },
      {
        id: 'product-12',
        name: 'Squared Sunglasses',
        price: '$45.99',
        brand: 'Zara',
        image: '',
        isLiked: false,
        isSaved: false,
      },
    ],
  },
]

