export interface WardrobeItem {
  id: string
  name: string
  category: string
  brand: string
  image: string
  description?: string
  dressCodes: string[]
  seasons: string[]
  colors: string[]
  length: string
  fabrics: string[]
  allowInStyling: boolean
  processed: boolean
  processing?: boolean
}

export const sampleWardrobeItems: WardrobeItem[] = [
  {
    id: '1',
    name: 'Basic Quarter-Zip Sweatshirt',
    category: 'Top',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    dressCodes: ['casual'],
    seasons: ['fall', 'winter'],
    colors: ['#95111F'],
    length: 'Normal',
    fabrics: ['polyester', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '2',
    name: 'Basic Quarter-Zip Sweatshirt',
    category: 'Bottom',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    dressCodes: ['casual'],
    seasons: ['fall', 'winter'],
    colors: ['#95111F'],
    length: 'Normal',
    fabrics: ['polyester', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '3',
    name: 'Basic Quarter-Zip Sweatshirt',
    category: 'Bags',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    dressCodes: ['casual'],
    seasons: ['fall', 'winter'],
    colors: ['#95111F'],
    length: 'Normal',
    fabrics: ['polyester', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '4',
    name: 'Basic Quarter-Zip Sweatshirt',
    category: 'Top',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    dressCodes: ['casual'],
    seasons: ['fall', 'winter'],
    colors: ['#95111F'],
    length: 'Normal',
    fabrics: ['polyester', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '5',
    name: 'Basic Quarter-Zip Sweatshirt',
    category: 'Top',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    dressCodes: ['casual'],
    seasons: ['fall', 'winter'],
    colors: ['#95111F'],
    length: 'Normal',
    fabrics: ['polyester', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '6',
    name: 'Basic Quarter-Zip Sweatshirt',
    category: 'Outerwear',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    dressCodes: ['casual'],
    seasons: ['fall', 'winter'],
    colors: ['#95111F'],
    length: 'Normal',
    fabrics: ['polyester', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '7',
    name: 'Basic Quarter-Zip Sweatshirt',
    category: 'Outerwear',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    dressCodes: ['casual'],
    seasons: ['fall', 'winter'],
    colors: ['#95111F'],
    length: 'Normal',
    fabrics: ['polyester', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '8',
    name: 'Basic Quarter-Zip Sweatshirt',
    category: 'Jewelry',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'A stylish and polished look for a brunch at ETHGlobal Conference in Argentina.',
    dressCodes: ['casual'],
    seasons: ['fall', 'winter'],
    colors: ['#95111F'],
    length: 'Normal',
    fabrics: ['polyester', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '9',
    name: 'Classic Button-Down Shirt',
    category: 'Tops',
    brand: 'H&M',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Perfect for business casual occasions.',
    dressCodes: ['business', 'smart-casual'],
    seasons: ['spring', 'summer', 'fall'],
    colors: ['#2C3E50', '#34495E'],
    length: 'Normal',
    fabrics: ['cotton', 'linen'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '10',
    name: 'Summer Linen Blazer',
    category: 'Outerwear',
    brand: 'Uniqlo',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Lightweight and breathable for warm weather.',
    dressCodes: ['business', 'formal', 'smart-casual'],
    seasons: ['spring', 'summer'],
    colors: ['#E8E8E8', '#F5F5F5'],
    length: 'Normal',
    fabrics: ['linen', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '11',
    name: 'Denim Jacket',
    category: 'Outerwear',
    brand: 'Levi\'s',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Timeless denim jacket for casual outings.',
    dressCodes: ['casual', 'smart-casual'],
    seasons: ['spring', 'fall'],
    colors: ['#1E3A5F', '#2E5090'],
    length: 'Normal',
    fabrics: ['denim', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '12',
    name: 'Wool Winter Coat',
    category: 'Outerwear',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Warm and cozy for cold winter days.',
    dressCodes: ['casual', 'smart-casual'],
    seasons: ['winter'],
    colors: ['#1A1A1A', '#2D2D2D'],
    length: 'Long',
    fabrics: ['wool', 'polyester'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '13',
    name: 'Silk Evening Blouse',
    category: 'Tops',
    brand: 'Mango',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Elegant silk blouse for formal events.',
    dressCodes: ['formal', 'business'],
    seasons: ['spring', 'summer', 'fall'],
    colors: ['#FFD700', '#FFA500'],
    length: 'Normal',
    fabrics: ['silk', 'polyester'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '14',
    name: 'Athletic Performance Tee',
    category: 'Tops',
    brand: 'Nike',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Moisture-wicking fabric for active wear.',
    dressCodes: ['sporty', 'casual'],
    seasons: ['spring', 'summer', 'fall'],
    colors: ['#000000', '#FFFFFF'],
    length: 'Normal',
    fabrics: ['polyester', 'spandex'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '15',
    name: 'Leather Moto Jacket',
    category: 'Outerwear',
    brand: 'AllSaints',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Edgy leather jacket for a bold look.',
    dressCodes: ['casual', 'smart-casual'],
    seasons: ['fall', 'winter'],
    colors: ['#000000', '#1C1C1C'],
    length: 'Normal',
    fabrics: ['leather', 'polyester'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '16',
    name: 'Chiffon Floral Dress',
    category: 'Tops',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Light and airy for spring and summer.',
    dressCodes: ['casual', 'smart-casual'],
    seasons: ['spring', 'summer'],
    colors: ['#FF69B4', '#FFB6C1', '#FFC0CB'],
    length: 'Long',
    fabrics: ['chiffon', 'polyester'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '17',
    name: 'Cashmere Sweater',
    category: 'Tops',
    brand: 'Everlane',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Luxurious cashmere for ultimate comfort.',
    dressCodes: ['casual', 'smart-casual', 'business'],
    seasons: ['fall', 'winter'],
    colors: ['#8B4513', '#A0522D'],
    length: 'Normal',
    fabrics: ['cashmere', 'wool'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '18',
    name: 'Cotton T-Shirt',
    category: 'Tops',
    brand: 'Gap',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Essential basic tee for everyday wear.',
    dressCodes: ['casual'],
    seasons: ['spring', 'summer', 'fall'],
    colors: ['#4169E1', '#0000FF'],
    length: 'Normal',
    fabrics: ['cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '19',
    name: 'Trench Coat',
    category: 'Outerwear',
    brand: 'Burberry',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Classic trench coat for rainy days.',
    dressCodes: ['business', 'formal', 'smart-casual'],
    seasons: ['spring', 'fall'],
    colors: ['#8B7355', '#A0826D'],
    length: 'Long',
    fabrics: ['cotton', 'polyester'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '20',
    name: 'Knit Cardigan',
    category: 'Outerwear',
    brand: 'COS',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Cozy cardigan for layering.',
    dressCodes: ['casual', 'smart-casual'],
    seasons: ['spring', 'fall', 'winter'],
    colors: ['#9370DB', '#8A2BE2'],
    length: 'Normal',
    fabrics: ['wool', 'acrylic'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '21',
    name: 'Sneakers',
    category: 'Footwear',
    brand: 'Adidas',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Comfortable sneakers for daily activities.',
    dressCodes: ['casual', 'sporty'],
    seasons: ['spring', 'summer', 'fall', 'winter'],
    colors: ['#000000', '#FFFFFF'],
    length: 'Normal',
    fabrics: ['leather', 'canvas', 'rubber'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '22',
    name: 'Leather Ankle Boots',
    category: 'Footwear',
    brand: 'Dr. Martens',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Durable boots for all seasons.',
    dressCodes: ['casual', 'smart-casual'],
    seasons: ['fall', 'winter'],
    colors: ['#000000', '#2F2F2F'],
    length: 'Normal',
    fabrics: ['leather', 'rubber'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '23',
    name: 'Canvas Tote Bag',
    category: 'Bags',
    brand: 'Everlane',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Spacious tote for everyday essentials.',
    dressCodes: ['casual', 'smart-casual'],
    seasons: ['spring', 'summer', 'fall', 'winter'],
    colors: ['#D2691E', '#CD853F'],
    length: 'Normal',
    fabrics: ['canvas', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '24',
    name: 'Leather Crossbody Bag',
    category: 'Bags',
    brand: 'Coach',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Elegant crossbody for special occasions.',
    dressCodes: ['formal', 'business', 'smart-casual'],
    seasons: ['spring', 'summer', 'fall', 'winter'],
    colors: ['#8B4513', '#A0522D'],
    length: 'Normal',
    fabrics: ['leather'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '25',
    name: 'Wool Scarf',
    category: 'Accessories',
    brand: 'Zara',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Warm scarf for winter months.',
    dressCodes: ['casual', 'smart-casual'],
    seasons: ['fall', 'winter'],
    colors: ['#DC143C', '#B22222'],
    length: 'Long',
    fabrics: ['wool', 'acrylic'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '26',
    name: 'Silver Necklace',
    category: 'Jewelry',
    brand: 'Tiffany & Co.',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Delicate silver necklace for any occasion.',
    dressCodes: ['formal', 'business', 'casual', 'smart-casual'],
    seasons: ['spring', 'summer', 'fall', 'winter'],
    colors: ['#C0C0C0', '#E8E8E8'],
    length: 'Normal',
    fabrics: ['silver'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '27',
    name: 'Chino Pants',
    category: 'Bottoms',
    brand: 'Banana Republic',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Versatile chinos for business casual.',
    dressCodes: ['business', 'smart-casual', 'casual'],
    seasons: ['spring', 'summer', 'fall'],
    colors: ['#4B0082', '#6A0DAD'],
    length: 'Normal',
    fabrics: ['cotton', 'polyester'],
    allowInStyling: true,
    processed: true,
  },
  {
    id: '28',
    name: 'Jeans',
    category: 'Bottoms',
    brand: 'Levi\'s',
    image: '/images/onboarding/wardrobe-cloth-1.png',
    description: 'Classic denim jeans for everyday wear.',
    dressCodes: ['casual', 'smart-casual'],
    seasons: ['spring', 'summer', 'fall', 'winter'],
    colors: ['#191970', '#000080'],
    length: 'Normal',
    fabrics: ['denim', 'cotton'],
    allowInStyling: true,
    processed: true,
  },
]

export const categories = [
  'All',
  'Tops',
  'Bottoms',
  'Outerwear',
  'Footwear',
  'Bags',
  'Accessories',
  'Jewelry',
  'Other pieces',
]

export const sortOptions = [
  'Newest',
  'Oldest',
  'Name A-Z',
  'Name Z-A',
]

